//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void IDAC0_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define DBG_URX_PIN             (15)
#define DBG_URX_PORT            (gpioPortC)

#define DBG_UTX_PIN             (14)
#define DBG_UTX_PORT            (gpioPortC)

#define GPIO_EM4WU4_PIN         (2)
#define GPIO_EM4WU4_PORT        (gpioPortF)

#define I2C0_SCL_PIN            (13)
#define I2C0_SCL_PORT           (gpioPortE)

#define I2C0_SDA_PIN            (12)
#define I2C0_SDA_PORT           (gpioPortE)

#define LEUART0_RX_PIN          (15)
#define LEUART0_RX_PORT         (gpioPortC)

#define LEUART0_TX_PIN          (14)
#define LEUART0_TX_PORT         (gpioPortC)

#define LORA_RST_PIN            (1)
#define LORA_RST_PORT           (gpioPortA)

#define LORA_URX_PIN            (11)
#define LORA_URX_PORT           (gpioPortE)

#define LORA_UTX_PIN            (10)
#define LORA_UTX_PORT           (gpioPortE)

#define MAG3110_INT_PIN         (9)
#define MAG3110_INT_PORT        (gpioPortC)

#define NTAG_FD_PIN             (2)
#define NTAG_FD_PORT            (gpioPortF)

#define PB_PIN_PIN              (4)
#define PB_PIN_PORT             (gpioPortC)

#define USART0_RX_PIN           (11)
#define USART0_RX_PORT          (gpioPortE)

#define USART0_TX_PIN           (10)
#define USART0_TX_PORT          (gpioPortE)

#define WAKEUP_AUX_PIN          (0)
#define WAKEUP_AUX_PORT         (gpioPortA)

// [User-defined pin name abstraction]$

#endif

